modLoader="javafml"
loaderVersion="[${loader_version},)"
license="Apache-2 by World of Nations"

[[mods]]
modId="won_skills"
version="${mod_version}"
displayName="WoN Skills"
authors="World of Nations Team"

description='''Skills for World of Nations'''

[[dependencies.won_skills]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},]"
    ordering="NONE"
    side="BOTH"

[[dependencies.won_skills]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"
